%% @author Igor compiler
%% @doc Compiler version: igorc 2.1.4
%% DO NOT EDIT THIS FILE - it is machine generated

-module(card_config).

-include("card_protocol.hrl").

-export([
    applications/0,
    log_lifetime_days/0
]).

-define(config, (cards:card_config(config))).

-spec applications() -> [card_protocol:application_key()].

applications() ->
    ?config#card_config.applications.

-spec log_lifetime_days() -> igor_types:int().

log_lifetime_days() ->
    ?config#card_config.log_lifetime_days.

