%% Author: Igor compiler
%% Compiler version: igorc 2.1.4
%% DO NOT EDIT THIS FILE - it is machine generated

-record(collection, {
    items :: [_T]
}).

-record(collection_slice, {
    total :: igor_types:int(),
    items :: [_T]
}).

-record(generic_response, {
    result :: boolean()
}).

-record(bad_request_error, {
    reason :: _T
}).

-record(unauthorized_error, {
}).

-record(forbidden_error, {
}).

-record(forbidden_error_ex, {
    reason :: _T
}).

-record(not_found_error, {
}).

-record(internal_server_error, {
    message :: binary()
}).

-record(not_implemented_error, {
    message = <<"Not yet implemented">> :: binary()
}).

