%% Author: Igor compiler
%% Compiler version: igorc 2.1.4
%% DO NOT EDIT THIS FILE - it is machine generated

-record(log_entry, {
    level :: data_protocol:log_level(),
    timestamp :: iso8601:datetimems(),
    data :: igor_json:json(),
    message :: binary(),
    msg_count :: igor_types:int(),
    seq_id :: igor_types:int()
}).

-record(invalid_data, {
    reason :: binary()
}).

