%% Author: Igor compiler
%% Compiler version: igorc 2.1.4
%% DO NOT EDIT THIS FILE - it is machine generated

-record(claims_guest, {
}).

-record(claims_web, {
    username :: binary()
}).

-record(claims_external, {
    key :: binary()
}).

-record(claims_zeus, {
    key :: binary()
}).

-record(login_request, {
    username :: binary(),
    password :: binary()
}).

-record(account, {
    id :: common_protocol:id(),
    rev :: igor_types:int(),
    username :: binary(),
    name :: binary() | 'undefined',
    email :: binary() | 'undefined',
    phone :: binary() | 'undefined',
    is_blocked :: boolean(),
    is_deleted :: boolean(),
    created_at :: iso8601:datetimems(),
    updated_at :: iso8601:datetimems()
}).

-record(component, {
    name :: binary(),
    versions :: [binary()],
    branches :: [binary()]
}).

-record(application, {
    name :: binary(),
    components :: [web_protocol:component()]
}).

-record(log_entry, {
    id :: common_protocol:id(),
    app :: binary(),
    component :: binary(),
    branch :: binary(),
    version :: binary(),
    level :: data_protocol:log_level(),
    timestamp :: iso8601:datetimems(),
    data :: igor_json:json(),
    message :: binary(),
    msg_count :: igor_types:int(),
    seq_id :: igor_types:int()
}).

-record(timeline_entry, {
    time_bin :: iso8601:datetimems(),
    num_trace :: igor_types:int(),
    num_debug :: igor_types:int(),
    num_info :: igor_types:int(),
    num_notice :: igor_types:int(),
    num_warning :: igor_types:int(),
    num_error :: igor_types:int(),
    num_fatal :: igor_types:int()
}).

-record(error_entry, {
    count :: igor_types:int(),
    message :: binary()
}).

-record(crash_report, {
    id :: common_protocol:id(),
    app :: binary(),
    component :: binary(),
    branch :: binary(),
    version :: binary(),
    game_engine :: binary(),
    username :: binary(),
    filename :: binary(),
    reason :: binary(),
    user_comment :: binary() | 'undefined',
    data :: igor_json:json(),
    created_at :: iso8601:datetimems()
}).

